### ISSUE TITLE
Aivu not progressing correctly?

### ISSUE THREAD

**Issue by Sutton618** [Vek17/TabletopTweaks-Reworks#20]
So I'll be honest and say I don't know if you intended for this or not, I can only read what you put in the release notes and compare things from there.

A lot of things you say that Aivu gets at later mythic ranks, Aivu gets them all at mythic rank 6.

For example:
Aivu gets 32 spell resistance upon reaching mythic level 6, but you say that this is not suppose to happen until mythic 9.
Aivu's tail gets the crit multiplier at mythic 6, but you say this occurs at level 7.
Aivu gets delirium breath at mythic 6, again this is suppose to occur at level 7?

See screenshots below for evidence of this:
![20230829203237_1](https://github.com/Vek17/TabletopTweaks-Reworks/assets/67255571/da62fe79-b65e-47d5-ac16-46257e5dbd5a)
![20230829203244_1](https://github.com/Vek17/TabletopTweaks-Reworks/assets/67255571/1ae01282-e5a5-493a-a6b7-cbfe3f0abc58)

Also, I don't know if Aivu gets this visual back at later mythic ranks, but I've noticed she has lost the blue azata glow that she usually gets at mythic rank 6 in vanilla (or with the setting off), see screenshots below for what I mean. Again, not sure if this is what you intended.

Aivu upgrade setting on:
![20230829204023_1](https://github.com/Vek17/TabletopTweaks-Reworks/assets/67255571/12da5391-84e6-4753-a70c-84f0e5e7c7f9)

Aivu upgrade setting off:
![20230829204507_1](https://github.com/Vek17/TabletopTweaks-Reworks/assets/67255571/33077cba-709a-4dba-b659-1028637c4161)

And last but not least. It's mentioned that Aivu's stats now upgrade as mythic rank increases, but turning the "Aivu upgrade" setting on and off and I don't see any difference in stats (aside from the breath weapon attack), only abilities. Again, this might be intended or a quirk or some other thing, but I just thought I'd make you aware.

Let me know if you need any more info!

**Comment by Vek17** [comment]
Do you have any other mods in use

**Comment by Vek17** [comment]
Fixed
https://github.com/Vek17/TabletopTweaks-Reworks/releases/tag/v1.2.9

**Comment by Sutton618** [comment]
Ah, good to hear you found the issue so promptly!

I considered as much about the stat thing, and I did see the mythic draconic growth racial bonus. I also was testing it going from mythic 5 -> 6 (as in, I load a game with me at mythic rank 5 and then level up to 6) with both the aivu upgrade setting on and then off, and there was no difference in the amount of stat increase. Maybe it was just a coincidence that this lines up with the vanilla stat increase? From mythic 5 to mythic 6, for example, Aivu goes from +6 racial bonus to strength, to +8. Again, it's probably nothing, but just wanna make sure!

Also, Aivu doesn't get to have blue aura? :<

**Comment by Vek17** [comment]
The aura was part of a bugged effect I removed technically so it isn't
there anymore
