### ISSUE TITLE
Since 2.2.3c games get stuck at 60%

### ISSUE THREAD

**Issue by Frodo123123** [Vek17/TabletopTweaks-Reworks#24]
**Describe the bug**
Since last patch, 2.2.3c whenever i want to load the game with TTT Mythic reworks it just stucks at 60%

**To Reproduce**
1. Go to 'ModFinder'
2. Install all 3 TTT mods
3. Open the game, it stucks at 60%

**Expected behavior**
The game should stuck at 60% within the first 3 steps. however, if you uninstall all 3 TTT mods, the game charges normally.

**Additional context**
This started since 2.2.3c, i have a Run finishing Act 2 which i play entirely with TTT mods and it worked well until the last patch

**Comment by Vek17** [comment]
I am not able to reproduce. I am able to load into 2.2.3c with
TTT-Core 0.71
TTT-Base 2.6.3
TTT-Reworks 1.3.1
TTT-Flanking 0.2.0

**Comment by Frodo123123** [comment]
I can record my screen if you want, i don't know if i can upload the video here...

**Comment by Vek17** [comment]
A player.log would be more useful

In %appdata%/../locallow/Owlcat Games

But everything up to date should just work, ive had no other reports of
issues and a load failure should trivially reproduce in my test setup

**Comment by Frodo123123** [comment]
[Player.log](https://github.com/Vek17/TabletopTweaks-Reworks/files/13711400/Player.log)
Honestly i know nothing about this, appreciate your help.

**Comment by Vek17** [comment]
O.o this looks bizarre, verify your game files. You are failing when trying to unpack a vanilla blueprint with an illegal format

**Comment by Frodo123123** [comment]
I'm pretty sure i've already done that... but i can be wrong maybe i did that with BG3 (which i've been also having problems haha) i'm verifying right now, i'll keep you updated.

**Comment by Vek17** [comment]
I mention it because the error specifically is taking place when it tried to read the packed binary gamefiles and it throws a nonsense error

InvalidOperationException: Expected Prerequisite.IsFeatureSelectionWhiteList but got IsFeatureSؽ   )  -(

**Comment by Vek17** [comment]
That or some other mod is doing something very not normal and I am running into it? Does the game load with onyl TTT loaded

**Comment by Frodo123123** [comment]
Ok... when this finish verifying i'll try start the game with all the mods, if still doesn't work i'll try only with TTT

**Comment by Frodo123123** [comment]
It found 1 corrupted file but it still doesn't load. I'll try with TTT

**Comment by Frodo123123** [comment]
Well nevermind, it works now, pretty slow loading but it works. Thank you for your help! you're the best
