### ISSUE TITLE
Abundant casting does not reduce spells available

### ISSUE THREAD

**Issue by WinterOrchid** [Vek17/TabletopTweaks-Reworks#26]
> Abundant Casting
> Now grants two bonus casts instead of 4.

This change does not appear to have been implemented. The text selecting the feat still reads abundant casting as giving four extra casts, and four extra spells are also given on selection.

**Comment by Vek17** [comment]
Text is out of date, it is 4,3,2 for abundant, improved, greater now

**Comment by WinterOrchid** [comment]
Thanks for the update (and your mods).
