### ISSUE TITLE
Ascendant Bloodline - Unable to Select

### ISSUE THREAD

**Issue by Azr-e** [Vek17/TabletopTweaks-Reworks#4]
The mythic ability Bloodline Ascendance cannot be taken after patch 1.3.5e.  Tried using both sorcerer and crossblood sorcerer, checked with celestial, dragon (white), and undead bloodlines. Prerequisites show as green but the ability remains greyed out and unable to be selected. 
Disabling Reworks and leaving Base and Core enabled allow for Bloodline Ascendance to once again be selected properly.

**Comment by Vek17** [comment]
This... does not make sense to me as Reworks does not interact with Bloodlines at all. What level were you when doing this? This sounds like an alternate capstone edge case to me.

**Comment by Azr-e** [comment]
I tried at several character levels and mythic levels, but without reworks it works at any mythic or character level.

**Comment by Vek17** [comment]
Okay I tested without reworks and with and wasn't able to pick in either case. Pretty sure I know what the issue is though and it is related to alternate capstones.

**Comment by Azr-e** [comment]
I just retried and it happened with Base and Core  enabled as well, so I guess I made a mistake in trying to repro it the first time. Glad I was able to bring it to your attention though.

**Comment by Azr-e** [comment]
That fixes the issue.
