### ISSUE TITLE
Trickster Stealth not working

### ISSUE THREAD

**Issue by mccalas89** [Vek17/TabletopTweaks-Reworks#7]
Using trickster stealth rank 1 (or 2) in combat doesn't require enemies with see invisibility or true sight to roll perception. They just see you and continue to attack.

**Comment by Vek17** [comment]
It works the same as normal invisibility, and afaik that follows RAW

**Comment by mccalas89** [comment]
Ok then, maybe I just misunderstand what is supposed to do, I have limited experience with Pathfinder.

The description says you can enter stealth in combat, and that this invisibility shouldn't be broken by true sight, see invisibility or thoughtsense.

Using the stealth ability against enemies without see invisibility causes them to stop targeting you until they roll perception against your stealth skill. But using it against enemies with see invisibility does nothing. 

Help me understand how this should work?

**Comment by Vek17** [comment]
Effectively it works just like the invisibility spells, which have some conditional stealth condition activation that are usually not applicable (interacts with a few class features iirc).

What it does do is grant you the invisible condition that is immune to divination.

**Comment by mccalas89** [comment]
So it's basically a move -action free invisibility without the +20 stealth bonus? And it shouldn't cause enemies to re-roll perception against you if they've already started combat?

**Comment by Vek17** [comment]
Correct

**Comment by mccalas89** [comment]
Ok. I guess I was confused because it caused normal enemies to re-roll perception against you. So I thought it would work the same against true seeing. Still confused, but thanks for the help.
